#!/usr/bin/env bash

set -e

function setup_filer {
    gcloud compute ssh --zone $zone --ssh-flag=-L3000:localhost:3000 polyaxon-nfs-vm --command="mkdir -m 777 -p /data/upload /data/data /data/outputs /data/logs /data/repos"
}


function update_kubectl {
    local readonly zone="$1"
    local readonly name="$2"
    gcloud container clusters get-credentials --zone $zone $name
}


function render_configs {
    export polyaxon_password="$1"
    export filer_ip=`gcloud --project ${project} compute instances describe polyaxon-nfs-vm --zone=${zone} --format='value(networkInterfaces[0].networkIP)'`
    envsubst < configs/polyaxon-config.yml.tmpl > configs/polyaxon-config.yml
    envsubst < configs/data-pvc.yml.tmpl > configs/data-pvc.yml
    envsubst < configs/outputs-pvc.yml.tmpl > configs/outputs-pvc.yml
    envsubst < configs/upload-pvc.yml.tmpl > configs/upload-pvc.yml
    envsubst < configs/logs-pvc.yml.tmpl > configs/logs-pvc.yml
    envsubst < configs/repos-pvc.yml.tmpl > configs/repos-pvc.yml
}

function install_polyaxon {
    set +e
    kubectl create namespace polyaxon
    kubectl create -f configs/data-pvc.yml -n polyaxon
    kubectl create -f configs/outputs-pvc.yml -n polyaxon
    kubectl create -f configs/upload-pvc.yml -n polyaxon
    kubectl create -f configs/logs-pvc.yml -n polyaxon
    kubectl create -f configs/repos-pvc.yml -n polyaxon
    kubectl --namespace kube-system create sa tiller
    kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
    helm init --service-account tiller

    helm repo add polyaxon https://charts.polyaxon.com
    helm repo update
    set -e
    helm install polyaxon/polyaxon --name=polyaxon --namespace=polyaxon -f configs/polyaxon-config.yml
}


project="$1"
zone="$2"
name="$3"
password="$4"

setup_filer $zone
update_kubectl $zone $name
render_configs $password
install_polyaxon
