#!/usr/bin/env bash

set -e


function update_kubectl {
    local readonly zone="$1"
    local readonly name="$2"
    gcloud container clusters get-credentials --zone $zone $name
}


function render_configs {
    export hostname="$1"
    export polyaxon_password="$2"
    envsubst < configs/polyaxon-config.yml.tmpl > configs/polyaxon-config.yml
}

function install_polyaxon {
    set +e
    local readonly tls_dir="$1"
    kubectl create namespace polyaxon
    kubectl --namespace kube-system create sa tiller
    kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
    kubectl create secret tls polyaxon-tls --namespace polyaxon --key "$tls_dir/privkey.pem" --cert "$tls_dir/fullchain.pem"
    sleep 15
    helm init --service-account tiller
    sleep 10

    helm repo add polyaxon https://charts.polyaxon.com
    helm repo update
    set -e
    # Need a better way to check readiness :(
    sleep 120
    helm install -n polyaxon --name=nginx stable/nginx-ingress
    helm install polyaxon/polyaxon --name=polyaxon --namespace=polyaxon -f configs/polyaxon-config.yml
}


project="$1"
zone="$2"
name="$3"
hostname="$4"
tls_base="$5"
password="$6"

update_kubectl $zone $name
render_configs $hostname $password
install_polyaxon "$tls_base/$hostname"
